name: relearn

on:
  schedule:
    - cron: '0 12 * * *' # 21:00 JST

jobs:
  start:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: node-dependencies-${{ hashFiles('package-lock.json') }}
      - name: Install JavaScript dependencies
        run: |
          npm ci
      - name: Start
        run: |
         npm run build && npm start
        env:
          GOOGLE_DRIVE_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
